print("1.- In blockbench with the geometry_2 model and the texture loaded select the full model")
print("2.- Click create texture icon, you can find it next to the import texture in the textures panel")
print("3.- Set as true UV box then select the desired pixel density and click accept")
print("4.- On the file panel select convert proyect then select the format as legacy bedrock model, then accept")
print("5.- Save the model as bedrock geometry file with the name of geometry_done or any other name")
print("6.- Do not forget to save the texture with the name as desired")
print("All cubes that were between 0 - 1 were scaled because they are incompatible with 4D Skins and need to be adjusted with inflate cubes in blockbench")
