print("1.- In blockbench with the geometry_2 model and the texture loaded select the full model")
print("2.- Click create texture icon, you can find it next to the import texture in the textures panel")
print("3.- Select as true the UV box then select desired pixel density and click accept")
print("4.- On file select convert proyect then select in format legacy bedrock model, the accept")
print("5.- Save the model as bedrock geometry file with the name of geometry_3_uvfix")
print("6.- Save texture name as desired")
print("All cubes that were scaled because they are incompatible with 4D Skins now need to be adjusted with inflate cubes")